### ISSUE TITLE
Documentation: Clarify which version of ArangoDB to use

### ISSUE THREAD

**Issue by lostpebble** [cw00dw0rd/ArangoBnB#35]
Going to download and play with the dataset today. Just noticed when I got to the point of downloading ArangoDB from the site, I wasn't sure which version to go for (I know Enterprise would be okay either way) - but would be nice to know which version this project aims to be compatible with.

Also should clarify the minimum version number required for the project- I assume its 3.8 for the new geo features.

**Comment by cw00dw0rd** [comment]
Good point now that we have nightly builds up I will update the readme. 
Since 3.8 is the targeted version, using the nightly build is the best way to test things. 

Here is the nightly build page for more info: [https://www.arangodb.com/nightly-builds/](https://www.arangodb.com/nightly-builds/)

**Comment by lostpebble** [comment]
Great, think that clarifies it all pretty nicely- thanks.

**Comment by lostpebble** [comment]
```
docker run -d -e ARANGO_ROOT_PASSWORD="test" -p 8529:8529 arangodb/arangodb-preview:devel-nightly
```

So I ran this to start the container- but the root password was not `test` as expected- it was just blank. I can see that this env variable has definitely been set on the container. Is the ENV variable incorrect here?

**Comment by cw00dw0rd** [comment]
I am following up on this as I have experienced the same thing. It does seem to set it to be blank.

**Comment by cw00dw0rd** [comment]
> ```
> docker run -d -e ARANGO_ROOT_PASSWORD="test" -p 8529:8529 arangodb/arangodb-preview:devel-nightly
> ```
> 
> So I ran this to start the container- but the root password was not `test` as expected- it was just blank. I can see that this env variable has definitely been set on the container. Is the ENV variable incorrect here?

The dev team has added a new image for 3.8.0 so the new docker tag to pull is `3.8.0-nightly` and includes the fix for this issue, try running:
`docker run -d -e ARANGO_ROOT_PASSWORD="test" -p 8529:8529 arangodb/arangodb-preview:3.8.0-nightly`

**Comment by lostpebble** [comment]
Cool, can confirm that image works with the set password now.
