### ISSUE TITLE
Frontend: Destination Search Bar

### ISSUE THREAD

**Issue by cw00dw0rd** [cw00dw0rd/ArangoBnB#5]
The current "Where to?" input needs to be functional. It is currently just a placeholder that does nothing.

This will have some dependence on the [backend](https://github.com/cw00dw0rd/ArangoBnB/labels/backend) and potentially overlap with #4 .

**Comment by Simran-B** [comment]
Geocoding plugin for leaflet.js to search for an address etc. and get a location back:
https://github.com/smeijer/leaflet-geosearch

OSM's Nominatim service should work for our purposes and doesn't require an API key:
https://nominatim.openstreetmap.org/search?q=brandenburg%20gate
https://nominatim.openstreetmap.org/search.php?q=brandenburg%20gate&polygon_geojson=1&format=jsonv2
